# Generated by Django 6.0.4 on 2026-04-13 11:41

import apps.content.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text='CSS icon class or emoji', max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.content.models.category_image_path)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (ascending)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=600, unique=True)),
                ('thumbnail', models.ImageField(blank=True, help_text='Cover image shown in listing pages', null=True, upload_to=apps.content.models.content_thumbnail_path)),
                ('excerpt', models.TextField(blank=True, help_text='Short summary shown in cards/previews', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Display label for this media item', max_length=300)),
                ('type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('youtube', 'YouTube'), ('iframe', 'iFrame / Embed')], max_length=20)),
                ('file', models.FileField(blank=True, help_text='Upload file directly (image, audio, video)', null=True, upload_to=apps.content.models.media_file_path)),
                ('url', models.URLField(blank=True, help_text='YouTube URL, iframe src URL, or any external media link', null=True)),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional preview image shown before media opens', null=True, upload_to='media_thumbnails/')),
                ('mime_type', models.CharField(blank=True, help_text='Detected/stored MIME type, e.g. audio/mpeg, video/mp4, image/png', max_length=100, null=True)),
                ('size_kb', models.PositiveIntegerField(blank=True, help_text='File size in KB (auto-populated on upload)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='content.content')),
            ],
            options={
                'verbose_name': 'Content Media',
                'verbose_name_plural': 'Content Media',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(help_text='TinyMCE rich-text HTML. May contain inline media shortcodes.')),
                ('position', models.CharField(choices=[('left', 'Left — Full Card'), ('right', 'Right — Expandable Accordion')], default='left', help_text='LEFT = full card | RIGHT = collapsible accordion', max_length=10)),
                ('is_open_by_default', models.BooleanField(default=False, help_text='RIGHT only — if True, accordion starts expanded on page load.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within its column')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.content')),
            ],
            options={
                'verbose_name': 'Content Section',
                'verbose_name_plural': 'Content Sections',
                'ordering': ['position', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sub_categories/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='content.category')),
            ],
            options={
                'verbose_name': 'Sub Category',
                'verbose_name_plural': 'Sub Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sub_sub_categories/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_sub_categories', to='content.subcategory')),
            ],
            options={
                'verbose_name': 'Sub-Sub Category',
                'verbose_name_plural': 'Sub-Sub Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='content',
            name='sub_sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='content.subsubcategory'),
        ),
        migrations.CreateModel(
            name='InlineMediaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_label', models.CharField(help_text="Visible text in the tag, e.g. 'সন্দেহ' or 'Audio'", max_length=200)),
                ('tag_key', models.CharField(help_text="Unique shortcode identifier per content, e.g. 'audio_001', 'img_gold'", max_length=100)),
                ('type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('youtube', 'YouTube'), ('iframe', 'iFrame / Embed'), ('text', 'Text / Definition')], max_length=20)),
                ('popup_body', models.TextField(blank=True, help_text='Used when type=Text. Shown as the popup content (plain text or HTML).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inline_tags', to='content.content')),
                ('media', models.ForeignKey(blank=True, help_text='Leave empty if tag type is Text/Definition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inline_tags', to='content.contentmedia')),
            ],
            options={
                'verbose_name': 'Inline Media Tag',
                'verbose_name_plural': 'Inline Media Tags',
                'ordering': ['tag_key'],
                'unique_together': {('content', 'tag_key')},
            },
        ),
    ]
